### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JackLeerson** [darkfishtech/roc-issue-tracker#1]
**Bug Description**
Privacy error occurring on https://manage.roc.org.au/, and no trips loading on https://roc.org.au/trips/

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://manage.roc.org.au/
2. See error

**Expected behaviour**
A non-scary privacy error 😁

**Screenshots**
![image](https://github.com/darkfishtech/roc-issue-tracker/assets/77082983/200deca4-5fc8-4188-972c-89a64f624c4f)
![image](https://github.com/darkfishtech/roc-issue-tracker/assets/77082983/22d09aa2-f424-4ed7-8ef3-d156ceb2eb62)

**Desktop (please complete the following information):**
 - Windows
 - Chrome and Edge

**Smartphone (please complete the following information if applicable; else remove):**
 - Android
 - Chrome and Edge

**Comment by darkfishy** [comment]
Thanks for reporting this. It has now been fixed 😄
